# Distributed under the terms of the GNU General Public License v3.
# $Header: $

EAPI=2

inherit latex-package

DESCRIPTION="Generated by g-CTAN: Additional font axes for LaTeX."
HOMEPAGE="http://www.ctan.org/
	http://launchpad.net/g-ctan"
SRC_URI="http://mirror.ctan.org/systems/texlive/tlnet//archive/fontaxes.tar.xz -> fontaxes-24880.tar.xz source? ( http://mirror.ctan.org/systems/texlive/tlnet//archive/fontaxes.source.tar.xz -> fontaxes-24880.source.tar.xz ) doc? ( http://mirror.ctan.org/systems/texlive/tlnet//archive/fontaxes.doc.tar.xz -> fontaxes-24880.doc.tar.xz )"
LICENSE="LPPL-1.21.3"

SLOT="0"
KEYWORDS="x86"

IUSE=" doc  source "
DEPEND=""
RDEPEND=""

S=${WORKDIR}

pkg_info() {
	einfo "This ebuild has been generated by the g-CTAN program, which"
	einfo "makes the TeXLive packages available to Gentoo users through"
	einfo "their standard package manager."
}

# Can go with EAPI=3
src_unpack() {
	for i in ${A}
	do
		xz -dc -- "${DISTDIR}/${i}" | tar xof - || die
	done
}

src_install() {
	dodir /usr/share/texmf-site/
	cp -R "${S}"/* "${D}"//usr/share/texmf-site//
}

pkg_postinst() {
	elog
	elog "This ebuild has been generated by app-portage/g-ctan."
	elog
	elog "The version identifier ${PV} for this ebuild has nothing to do with"
	elog "the real version of the package, but is a revision of the source code"
	elog "management system of TeXLive.  Keep this in mind when dealing with"
	elog "people/programs outside of Gentoo systems."
	elog
	elog "Also note that the dependencies were not checked, so you"
	elog "might need to install other packages, too."

	latex-package_pkg_postinst
}

## Local Variables:
## mode: ebuild
## End:
